### ISSUE TITLE
With RC5 the authenticated event is not received

### ISSUE THREAD

**Issue by ckapilla** [auth0-samples/auth0-angularjs2-systemjs-sample#30]
Updating to RC% like so:
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",

and also to lock v 10.2.0 the authenticated event does not get fired after calling lock.show and logging in

**Comment by ashishdasnurkar** [comment]
I can reproduce this. After some investigation it seems when using ng2 rc5, the returned hash parameters to the callback url are URI encoded and lock/auth0js is not able to parse them properly. More specifically if you debug then https://github.com/auth0/lock/blob/master/src/core/web_api.js#L84 results in calling Auth0.js parseHash function here https://github.com/auth0/auth0.js/blob/d0680993bebaf4efaebf229049a15203b4445dda/index.js#L444 parsed_qs is an object with incorrect values for eg. instead of 

```
{
 "access_token" : "some_value",
"id_token" : "some_value",
"token_type" : "Bearer"
}
```

it is 

```
{"base":{"access_token=some_value&id_token=some_value&token_type=Bearer":""}}
```

What's interesting though is that with rc4 and rc5, if you observe network traffic, the response from auth0 (i.e. the hash params passed to callback url) is not URI encoded however when displayed in url or accessed via global.location.hash they are URI encoded.

**Comment by ckapilla** [comment]
Very interesting – thanks for your research on this! Looking forward to a resolution.

 

Chris

**Comment by bjcull** [comment]
FYI, my temporary workaround:
```
<script src="//cdn.auth0.com/w2/auth0-7.0.3.min.js"></script>
```
```
    auth0 = new Auth0({
        domain: "[AUTH0_DOMAIN]",
        clientID: "[AUTH0_CLIENT_ID]",
    });
```
```
    router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        if (window.location.href.indexOf("access_token%3D") >= 0) {
          console.log("TEMPORARY HACK: Detected encoded URL AccessToken. Manually parsing id_token. See https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/issues/30");
          var parsedData = this.auth0.parseHash(decodeURIComponent(window.location.href));
          console.log(parsedData);
          this.setIdToken(parsedData.idToken);
        }
      }
    });
```

**Comment by ckapilla** [comment]
thanks for sharing that Ben,I haven't messed with router events yet, so that is a very instructional example. Can't wait to try it out!

**Comment by ashishdasnurkar** [comment]
Lock 10.2.2 is released that fixes this issue.
