### ISSUE TITLE
Encounter problems installing dependencies

### ISSUE THREAD

**Issue by nnats** [auth0-samples/auth0-angularjs2-systemjs-sample#47]
Using npm v 3.10.10, Node 6.9.4.

Executing npm install the following errors occurred:

1.- Deprecated modules:
![image](https://cloud.githubusercontent.com/assets/20141842/22231020/ab46b7ea-e1bf-11e6-9377-9643fe2b073d.png)

2.- Unmet peer dependency:
![image](https://cloud.githubusercontent.com/assets/20141842/22231055/d25ae018-e1bf-11e6-8e0c-869c73f9c97b.png)

3.- Warnings at the end:
![image](https://cloud.githubusercontent.com/assets/20141842/22231071/e7ebd5ea-e1bf-11e6-8c4b-7603e52b23a3.png)

Executing npm install --save auth0-lock:

![image](https://cloud.githubusercontent.com/assets/20141842/22231093/0e607aa0-e1c0-11e6-91ec-23c3cc53b3eb.png)

**Comment by yfrolov** [comment]
Very same problem here.
NPM 4.0.5 & Node 7.4.0

**Comment by Amialc** [comment]
Hi, @nnats.
1. Samples doesn't use `node-uuid`, `minimatch` or `tough-cookies` packages (you can check it in `package.json` file), instead samples use packages that use that deprecated packages, so it should be fixed in those packages.
2.  Take look at [this](https://auth0.com/forum/t/unmet-peer-dependency-when-installing-angular2-jwt/3607/6). Also seems like it [known issue](https://github.com/auth0/angular2-jwt/issues/295) and related to angular2-jwt.
3. As you can see `fsevents` which is optional dependency can't be installed on your OS.

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-angular-samples) :)
